name: lawchat_frontend
description: "2025-2 MP Team Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  go_router: ^16.3.0
  flutter_slidable: ^4.0.3
  syncfusion_flutter_datepicker: ^31.2.10
  syncfusion_localizations: ^31.2.10
  syncfusion_flutter_core: ^31.2.10
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2
  app_links: ^6.0.0
  http: ^1.6.0
  shared_preferences: ^2.2.3
  firebase_core: ^3.2.0  # Added for FCM
  firebase_messaging: ^15.0.1 # Added for FCM

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
